version: "3.9"

services:
  rabbit:
    image: rabbitmq:4.1-management
    ports:
      - "15672:15672"   # web UI
      - "5672:5672"     # AMQP
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin